# Generated by Django 6.0.1 on 2026-01-18 23:24

from django.db import migrations
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


def load_initial_data(apps, schema_editor):
    # User = get_user_model()
    User = apps.get_model('auth', 'User')

    user = User.objects.create_user(
        first_name='John',
        last_name='Smith',
        username='jsmith'
    )

    user = User.objects.get(username='jsmith')

    Item = apps.get_model('inventory', 'Item')

    Item.objects.create(name='Classic Denim Jacket',
                        quantity=14,
                        description='A timeless layering piece made from durable indigo wash denim, featuring silver-tone buttons and a tailored fit.',
                        user=user
                        )
    Item.objects.create(name='Cashmere Crewneck Sweater',
                        quantity=42,
                        description='An ultra-soft, lightweight sweater knitted from premium Grade-A cashmere, perfect for seasonal transitions.',
                        user=user
                        )
    Item.objects.create(name='High-Waisted Chinos',
                        quantity=7,
                        description='Breathable cotton-twill trousers with a relaxed tapered leg and a flattering high-rise waist.',
                        user=user
                        )
    Item.objects.create(name='Water-Resistant Windbreaker',
                        quantity=89,
                        description='A functional outer shell featuring a sleek matte finish, adjustable hood, and zippered pockets for outdoor activities.',
                        user=user)
    Item.objects.create(name='Leather Chelsea Boots',
                        quantity=23,
                        description='Sleek, ankle-high boots with elastic side panels and a pull tab, crafted from polished full-grain leather.',
                        user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_description'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
